{% set name = "h2o" %}
{% set version = "3.36.0.3" %}


package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59e810c4d9b28d7c7f323bb191d92e7db83b95055cd646c5fa29bd77c50124bf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama >=0.3.8
    - future
    - python >=3.6
    - requests
    - tabulate
    - numpy

test:
  imports:
    - h2o
    - h2o.automl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h2oai/h2o-3
  summary: H2O, Fast Scalable Machine Learning, for python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
