{% set name = "h2o" %}
{% set version = "3.32.1.7" %}


package:
  name: {{ name|lower }}-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8ef8a416822fc4ef461c2a93af3728bc95879a1f3869c1828238c78d4b77b39

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorama >=0.3.8
    - future
    - python >=3.6
    - requests
    - tabulate

test:
  imports:
    - h2o
    - h2o.automl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/h2oai/h2o-3
  summary: H2O, Fast Scalable Machine Learning, for python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
